package edu.uniandes.ecos.ASE.app;                                                                                                                                                                                                                                                                                                                                              
import java.util.Enumeration;                                                                                                                                                                                                                                                                                                                                                   
import java.util.Hashtable;                                                                                                                                                                                                                                                                                                                                                     
import java.util.LinkedList;                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                
import FileManager.FileManager;                                                                                                                                                                                                                                                                                                                                                 
import LineOfCodeCounter.ClassCounter;                                                                                                                                                                                                                                                                                                                                          
public class App                                                                                                                                                                                                                                                                                                                                                                
{                                                                                                                                                                                                                                                                                                                                                                               
    public static void main( String[] args )                                                                                                                                                                                                                                                                                                                                    
    {                                                                                                                                                                                                                                                                                                                                                                           
		int totalProgramSize =0;                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                
        LinkedList<String> linkedList = FileManager.SearchFileByExetension("D:\\ECOS\\Proyects\\TAREA2\\mi-primera-app",".java");                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                
         for (String item : linkedList){                                                                                                                                                                                                                                                                                                                                        
         	 System.out.println("File Path = " + item);                                                                                                                                                                                                                                                                                                                         
         	 System.out.println("ClassName = " + ClassCounter.ClassCounter(FileManager.ReadFile(item)));                                                                                                                                                                                                                                                                        
			 int classLOC = 	ClassCounter.LineCounter(FileManager.ReadFile(item));                                                                                                                                                                                                                                                                                           
			 totalProgramSize+=classLOC;                                                                                                                                                                                                                                                                                                                                        
         	 System.out.println("Class Line of Code = " + classLOC);                                                                                                                                                                                                                                                                                                            
         	 Hashtable<String, Integer> hashTable =  ClassCounter.MethodName(FileManager.ReadFile(item));                                                                                                                                                                                                                                                                       
         	 System.out.println("Numbers of Methods In class =  " + hashTable.size() );                                                                                                                                                                                                                                                                                         
         	 Enumeration<String> names = hashTable.keys();                                                                                                                                                                                                                                                                                                                      
			while(names.hasMoreElements()) {                                                                                                                                                                                                                                                                                                                                    
				 String methodName = (String) names.nextElement();                                                                                                                                                                                                                                                                                                              
				 System.out.println("Method Name = " + methodName );                                                                                                                                                                                                                                                                                                            
				 System.out.println("Method Lines Of Code = " + hashTable.get(methodName));                                                                                                                                                                                                                                                                                     
			}                                                                                                                                                                                                                                                                                                                                                                   
			System.out.println("\n\n");			                                                                                                                                                                                                                                                                                                                                
         }                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                
         System.out.println("\t\tTotal Number of Lines = " + totalProgramSize);                                                                                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                                                                                                                                                           
}                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                